#!/usr/bin/env bash
# scheduling.sh — Scheduled daily runs via macOS launchd
#
# Installs two LaunchAgents that run the vault's daily workflows unattended:
#   - /today          every morning (default 06:00 local)
#   - /eod + /learned every evening (default 19:00 local)
#
# Why the runner scripts live OUTSIDE the vault:
#   Vaults default to ~/Documents, which is TCC-protected on macOS. A LaunchAgent
#   (running /bin/zsh) has no privacy grant to read files there, so a wrapper placed
#   inside the vault fails with "can't open input file" (exit 127). We therefore write
#   the wrappers to ~/Library/Application Support/<name>-scheduled/ (not protected) and
#   only `cd` into the vault at run time, which traversal does not require a TCC grant.
#
# The wrappers run `claude -p "<cmd>" --dangerously-skip-permissions` because the run is
# unattended — there is no human to approve permission prompts. Deny rules in
# settings.json are still honored.

# ── Helpers ──────────────────────────────────────────────────────────

# Sanitize a vault name into a launchd-label / filesystem-safe token.
_sched_safe_name() {
  echo "$1" | tr ' ' '-' | tr -cd '[:alnum:]._-'
}

# Prompt for a 24h hour, re-prompting until it is an integer in 0-23.
# Prompts go to stderr so the captured stdout is just the value.
_sched_prompt_hour() {
  local header="$1" prompt="$2" default="$3" value
  while true; do
    value=$(prompt_input "$header" "$prompt" "$default")
    if [[ "$value" =~ ^([0-9]|1[0-9]|2[0-3])$ ]]; then
      echo "$value"
      return 0
    fi
    log_warn "Enter an hour from 0 to 23." >&2
  done
}

# Write one runner wrapper. Args: dest_file vault_dir log_file name cmd
_sched_write_runner() {
  local dest_file="$1" vault_dir="$2" log_file="$3" name="$4" cmd="$5"
  {
    printf '%s\n' "#!/bin/zsh"
    printf '%s\n' "# Auto-generated by the Second Brain installer (lib/scheduling.sh)."
    printf '%s\n' "# Do not edit here — regenerate with: ./install.sh --update"
    printf '%s\n' "VAULT=\"${vault_dir}\""
    printf '%s\n' "LOG=\"${log_file}\""
    printf '%s\n' "NAME=\"${name}\""
    printf '%s\n' "CMD=\"${cmd}\""
    cat <<'BODY'
emulate -L zsh
# Load the user's environment (PATH, tokens like SLACK_USER_TOKEN, the claude function).
[[ -f "$HOME/.zprofile" ]] && source "$HOME/.zprofile" 2>/dev/null
[[ -f "$HOME/.zshrc" ]] && source "$HOME/.zshrc" 2>/dev/null
export PATH="$HOME/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$HOME/go/bin:$HOME/.cargo/bin:$PATH"

mkdir -p "${LOG:h}"
cd "$VAULT" || { echo "scheduled-run: vault not found: $VAULT" >&2; exit 1; }

echo "===== $NAME START $(date '+%Y-%m-%d %H:%M:%S %Z') =====" >> "$LOG"
command claude -p "$CMD" --dangerously-skip-permissions >> "$LOG" 2>&1
rc=$?
echo "===== $NAME END rc=$rc $(date '+%Y-%m-%d %H:%M:%S %Z') =====" >> "$LOG"
exit $rc
BODY
  } > "$dest_file"
  chmod +x "$dest_file"
}

# Write one launchd plist. Args: dest_file label runner_script hour minute log_file
_sched_write_plist() {
  local dest_file="$1" label="$2" runner="$3" hour="$4" minute="$5" log_file="$6"
  cat > "$dest_file" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key><array>
    <string>/bin/zsh</string>
    <string>${runner}</string>
  </array>
  <key>StartCalendarInterval</key><dict><key>Hour</key><integer>${hour}</integer><key>Minute</key><integer>${minute}</integer></dict>
  <key>StandardOutPath</key><string>${log_file}</string>
  <key>StandardErrorPath</key><string>${log_file}</string>
  <key>ProcessType</key><string>Background</string>
</dict></plist>
PLIST
}

# (Re)load a launchd agent idempotently. Args: label plist
_sched_load() {
  local label="$1" plist="$2" uid
  uid="$(id -u)"
  launchctl bootout "gui/${uid}/${label}" 2>/dev/null || true
  launchctl bootstrap "gui/${uid}" "$plist"
}

# ── Public entry point ───────────────────────────────────────────────

# setup_scheduling <vault_dir> <vault_name>
setup_scheduling() {
  local vault_dir="$1"
  local vault_name="$2"

  log_step "Scheduled daily runs (launchd)"

  if [[ "$(uname)" != "Darwin" ]]; then
    log_warn "Scheduled runs use macOS launchd — skipping on $(uname)."
    log_info "On Linux, wire the runner scripts into cron or a systemd timer instead."
    return 0
  fi

  if ! command -v claude >/dev/null 2>&1; then
    log_warn "claude CLI not found on PATH — install it before the scheduled runs will work."
  fi

  local safe_name today_hour eod_hour
  safe_name="$(_sched_safe_name "$vault_name")"
  [[ -z "$safe_name" ]] && safe_name="second-brain"  # names that strip to nothing

  today_hour=$(_sched_prompt_hour "Morning /today hour" "24h local hour to run /today (0-23)" "6")
  eod_hour=$(_sched_prompt_hour "Evening /eod hour" "24h local hour to run /eod + /learned (0-23)" "19")

  local runner_dir log_dir agents_dir
  runner_dir="${HOME}/Library/Application Support/${safe_name}-scheduled"
  log_dir="${HOME}/Library/Logs/${safe_name}-scheduled"
  agents_dir="${HOME}/Library/LaunchAgents"
  mkdir -p "$runner_dir" "$log_dir" "$agents_dir"

  # Runners
  _sched_write_runner "${runner_dir}/run-today.sh" "$vault_dir" "${log_dir}/today.log" \
    "/today" "/today"
  _sched_write_runner "${runner_dir}/run-eod.sh" "$vault_dir" "${log_dir}/eod.log" \
    "/eod + /learned" \
    "Run the /eod end-of-day workflow to completion, then run /learned to capture session context."

  # Plists
  local today_label eod_label today_plist eod_plist
  today_label="dev.secondbrain.${safe_name}-today"
  eod_label="dev.secondbrain.${safe_name}-eod"
  today_plist="${agents_dir}/${today_label}.plist"
  eod_plist="${agents_dir}/${eod_label}.plist"

  _sched_write_plist "$today_plist" "$today_label" "${runner_dir}/run-today.sh" "$today_hour" "0" "${log_dir}/today.launchd.log"
  _sched_write_plist "$eod_plist" "$eod_label" "${runner_dir}/run-eod.sh" "$eod_hour" "0" "${log_dir}/eod.launchd.log"

  _sched_load "$today_label" "$today_plist"
  _sched_load "$eod_label" "$eod_plist"

  log_success "Scheduled: /today at ${today_hour}:00, /eod + /learned at ${eod_hour}:00 (local, daily)"
  log_info "Runners: ${runner_dir}"
  log_info "Logs:    ${log_dir}"
  log_info "Test now: launchctl kickstart -k gui/$(id -u)/${today_label}"
  log_info "Note: claude.ai MCP connectors may be absent in headless runs; vault/GitHub/Granola steps still run."
}

# remove_scheduling <vault_name> — unload agents and delete plists (runners/logs kept).
remove_scheduling() {
  local vault_name="$1" safe_name uid
  safe_name="$(_sched_safe_name "$vault_name")"
  uid="$(id -u)"
  local today_label="dev.secondbrain.${safe_name}-today"
  local eod_label="dev.secondbrain.${safe_name}-eod"
  launchctl bootout "gui/${uid}/${today_label}" 2>/dev/null || true
  launchctl bootout "gui/${uid}/${eod_label}" 2>/dev/null || true
  rm -f "${HOME}/Library/LaunchAgents/${today_label}.plist" "${HOME}/Library/LaunchAgents/${eod_label}.plist"
  log_success "Removed scheduled runs for ${vault_name}"
}
